language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: PviHIKs7nOpda4dMyOcvzL66P+KUsN9FasxgqOkTkrdK4t1tlkDw4fgemel4VVmJNF/BUfUai5H8xqPqqQmVZbnyuMxSQE+KQVxDqFH/kNfezT7DYEcF4uoxHa8n/ly2AU6Bn2ofEE/9xZvZAkm0AyQsgDEd4pafHngD4rDC21fhK07AyxpzmeSAkH+K2cXMnlPX+s6vDbRuEYJMzKBl4/rLEZf9FmT2FARiC7l7EEAg/E7xBPNpd3ZfHIWvSm1RWTbsmY7hTRq/xNMAHZPTuXMnSIUzKH8XEIl2Q67vbF+y/7NlK6e2BwWsHXVbPC4+j1/u6MSIRB7u0uWajF6jEaEatK7zyufBXDfO6A0t156o86aXkiF9wDjoizX65uTO/bpWQYu5qhHy5Ww7hVTKsn6LSoHBgzBvT70bdi9OAIprmGE+af13V1miEgtxBiN6YGKp5krefAQjSw1RVN6dTwWK3zil4tav1R9WcMxPKTP1f+dhMgXfN2IW3Ma5HH1w2BGX8JZkFTtI0NYlkNT+ypPk3h+unM8QxJw7B7t7XvzNqsQxZSOoh0KTqLMRTWWx6nK9xZ/p5k8L2ftLY7w8EDqoFOIgyVLOLfh19RwS1xz95gVhtjslzovPMQqY2sVvm9ovwRF1F9TAolzpmN72NVPW/qqOdHYuiJXeKgQQ9DM=
